//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllittaMMC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string TextH { get; set; }
        public string TextP { get; set; }
        public string Image { get; set; }
    }
}
