//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllittaMMC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Additional_Info()
        {
            this.TourPackets = new HashSet<TourPacket>();
        }
    
        public int ID { get; set; }
        public string Location { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Min_Age { get; set; }
        public Nullable<int> Max_People { get; set; }
        public string Landing { get; set; }
        public string Check_In { get; set; }
        public string Check_Out { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourPacket> TourPackets { get; set; }
    }
}
