//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllittaMMC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A4490D_khaligchEntities : DbContext
    {
        public DB_A4490D_khaligchEntities()
            : base("name=DB_A4490D_khaligchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUS { get; set; }
        public virtual DbSet<Additional_Info> Additional_Info { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<HomeSlide> HomeSlides { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<OurTeam> OurTeams { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesHeader> ServicesHeaders { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TourPacket> TourPackets { get; set; }
        public virtual DbSet<TourSort> TourSorts { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
    }
}
