//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllittaMMC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourPacket
    {
        public int ID { get; set; }
        public string TourName { get; set; }
        public string TourDay { get; set; }
        public Nullable<int> HotelStar { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Additional_Info_ID { get; set; }
        public string Map_Tour { get; set; }
        public Nullable<int> TourSortID { get; set; }
    
        public virtual Additional_Info Additional_Info { get; set; }
        public virtual TourSort TourSort { get; set; }
    }
}
